package com.sofka.apidemo.model;

import javax.persistence.*;

//Entity: annotation that makes this class to be mapped to a DB
@Entity
//Table: annotation that binds this class to a DB table named "user"
@Table(name = "user")
public class UserModel {

//    Id: annotation for id attribute to be the primary key
    @Id
//    GeneratedValue: annotation that set id attribute as autogenerated
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    Column: annotation to make id attribute unique within the table
    @Column(unique = true, nullable = false)
    private Long id;
    private String name;
    private String email;
    private Integer priority;
    private Character genre;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Character getGenre() {
        return genre;
    }

    public void setGenre(Character genre) {
        this.genre = genre;
    }
}
